'''

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

'''


if __name__ == '__main__':
	triangle = lambda x: 0.5*x*(x+1)
	pentagonal = lambda x: 0.5*x*(3*x-1)
	hexagonal = lambda x: x*(2*x-1)

	triangleNumbers = {triangle(i):True for i in range(2,100000)}
	pentagonalNumbers = {pentagonal(i):True for i in range(2,100000)}
	hexagonalNumbers = [hexagonal(i) for i in range(2,50000)]

	for h in hexagonalNumbers:
		if h in pentagonalNumbers and h in triangleNumbers:
			print(h)








